"""Fix message fields

Revision ID: 7ff47df5500e
Revises: 2d2a67f50200
Create Date: 2026-04-28 00:39:36.794427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ff47df5500e"
down_revision: Union[str, Sequence[str], None] = "2d2a67f50200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column("messages", sa.Column("duration_ms", sa.Integer(), nullable=True))
    op.drop_column("messages", "confidence_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "confidence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("messages", "duration_ms")
    op.drop_column("messages", "confidence")
    # ### end Alembic commands ###
